# Generated by Django 4.1.4 on 2023-07-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_alter_product_image_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
