# Generated by Django 4.1.4 on 2023-07-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_cartitem_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="total",
        ),
    ]
