# Generated by Django 4.1.4 on 2023-07-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_remove_cartitem_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(null=True, upload_to="categories_images/"),
        ),
    ]
