# Generated by Django 4.1.4 on 2023-07-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating_range",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
