# Generated by Django 4.1.4 on 2023-07-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_product_rating_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="test Description", max_length=4000),
        ),
    ]
