# Generated by Django 4.1.4 on 2023-07-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_billingaddress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BillingAddress",
        ),
    ]
