# Generated by Django 4.1.4 on 2023-07-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_billing_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity_sold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
