# Generated by Django 4.1.4 on 2023-07-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0013_product_quantity_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                choices=[
                    ("", "Select Color"),
                    ("Black", "Black"),
                    ("White", "White"),
                    ("Red", "Red"),
                    ("Blue", "Blue"),
                    ("Green", "Green"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[
                    ("", "Select Size"),
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                ],
                default="",
                max_length=2,
            ),
        ),
    ]
