# Generated by Django 4.1.4 on 2023-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0017_color_product_size_product_remove_cartitem_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="order_color_size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("", "Select Color"),
                            ("Black", "Black"),
                            ("White", "White"),
                            ("Red", "Red"),
                            ("Blue", "Blue"),
                            ("Green", "Green"),
                        ],
                        default="no_color",
                        max_length=10,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("", "Select Size"),
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                        ],
                        default="no_size",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="color_product",
        ),
        migrations.DeleteModel(
            name="size_product",
        ),
    ]
