# Generated by Django 4.1.4 on 2023-07-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0019_alter_order_color_size_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_color_size",
            name="product",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.product",
            ),
            preserve_default=False,
        ),
    ]
