# Generated by Django 4.1.4 on 2023-07-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0020_order_color_size_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="order_color_size",
        ),
    ]
