# Generated by Django 4.1.4 on 2023-07-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0021_delete_order_color_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="color",
            field=models.CharField(
                choices=[
                    ("Black", "Black"),
                    ("White", "White"),
                    ("Red", "Red"),
                    ("Blue", "Blue"),
                    ("Green", "Green"),
                ],
                default="no_color",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.CharField(
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                ],
                default="no_size",
                max_length=10,
            ),
        ),
    ]
